# Generated by Django 4.1.7 on 2023-04-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
